# Generated by Django 5.1.1 on 2024-11-13 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('clien_p_id', models.AutoField(primary_key=True, serialize=False)),
                ('clien_c_nombre', models.CharField(max_length=50)),
                ('clien_b_activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('depto_p_id', models.AutoField(primary_key=True, serialize=False)),
                ('depto_c_nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Descripcion',
            fields=[
                ('desc_p_id', models.AutoField(primary_key=True, serialize=False)),
                ('desc_c_nombre', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('equip_p_id', models.AutoField(primary_key=True, serialize=False)),
                ('equip_c_nombre', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('estado_p_id', models.AutoField(primary_key=True, serialize=False)),
                ('estado_c_nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('perf_p_id', models.AutoField(primary_key=True, serialize=False)),
                ('perf_c_nombre', models.CharField(max_length=50)),
                ('perf_b_activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('prio_p_id', models.AutoField(primary_key=True, serialize=False)),
                ('prio_c_nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tiempo',
            fields=[
                ('tmpo_p_id', models.AutoField(primary_key=True, serialize=False)),
                ('tmpo_d_hora_inicio', models.DateTimeField(blank=True, null=True)),
                ('tmpo_d_hora_fin', models.DateTimeField(blank=True, null=True)),
                ('tmpo_n_duracion', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTicket',
            fields=[
                ('tip_p_id', models.AutoField(primary_key=True, serialize=False)),
                ('tip_c_nombre', models.CharField(max_length=50)),
                ('tip_c_detalle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Requerimiento',
            fields=[
                ('reque_p_id', models.AutoField(primary_key=True, serialize=False)),
                ('reque_c_detalle', models.CharField(max_length=50)),
                ('reque_c_observacion', models.CharField(max_length=50)),
                ('clien_p_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cliente')),
                ('tmpo_p_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tiempo')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuar_p_id', models.AutoField(primary_key=True, serialize=False)),
                ('usuar_c_nombre', models.CharField(max_length=100)),
                ('usuar_b_estado', models.BooleanField(default=True)),
                ('usuar_n_rut', models.IntegerField(blank=True, null=True)),
                ('depto_p_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.departamento')),
                ('equip_p_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.equipo')),
                ('perf_p_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_p_id', models.AutoField(primary_key=True, serialize=False)),
                ('clien_p_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cliente')),
                ('desc_p_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.descripcion')),
                ('estado_p_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.estado')),
                ('prio_p_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.prioridad')),
                ('reque_p_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.requerimiento')),
                ('tmpo_p_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tiempo')),
                ('tip_p_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tipoticket')),
                ('usuar_p_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.usuario')),
            ],
        ),
    ]
