# Generated by Django 5.1.1 on 2024-12-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='email',
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='default@gmail.com', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
