# Generated by Django 5.1.1 on 2024-11-21 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_tipoticket_tip_c_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
