# Generated by Django 4.2.5 on 2024-11-23 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descripcion',
            name='desc_c_nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='reque_c_detalle',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='reque_c_observacion',
            field=models.CharField(max_length=100),
        ),
    ]
