# Generated by Django 4.2.5 on 2024-12-03 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_descripcion_desc_c_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='archivos_adjuntos/'),
        ),
    ]
