# Generated by Django 4.2.5 on 2024-12-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_ticket_archivo_adjunto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='archivo_adjunto',
        ),
        migrations.CreateModel(
            name='ArchivoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='archivos_adjuntos/')),
                ('tickets', models.ManyToManyField(blank=True, related_name='archivos', to='app.ticket')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='archivos_adjuntos',
            field=models.ManyToManyField(blank=True, related_name='tickets_adjuntos', to='app.archivoadjunto'),
        ),
    ]
