# Generated by Django 4.2.5 on 2024-12-05 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_ticket_archivo_adjunto_archivoadjunto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='archivos_adjuntos',
        ),
        migrations.AddField(
            model_name='ticket',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='archivos_adjuntos/'),
        ),
        migrations.DeleteModel(
            name='ArchivoAdjunto',
        ),
    ]
