# Generated by Django 4.2.5 on 2024-12-06 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_ticket_archivo_adjunto_delete_archivoadjunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
